services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes: 
      - ./server/config.ini:/config.ini:ro
  

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=cliente
      - APELLIDO=1
      - DOCUMENTO=1
      - NACIMIENTO=1990-01-01
      - NUMERO=1
      - DATASET_PATH=/data/agency-1.csv
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data:/data:ro
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=cliente
      - APELLIDO=2
      - DOCUMENTO=2
      - NACIMIENTO=1990-01-01
      - NUMERO=2
      - DATASET_PATH=/data/agency-2.csv
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./.data:/data:ro
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
